import type {Metadata} from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const posts = await (await fetch('http://localhost:4000/posts')).json();

  return (
    <html lang="en">
      <body className="p-4">
        <nav className="flex gap-4 mb-2">
          <Link href="/" className="underline text-blue-400">
            Home
          </Link>
          <Link href="/about" className="underline text-blue-400">
            About
          </Link>
          <Link href="/blog/1" className="underline text-blue-400">
            blog1
          </Link>
          <Link href="/blog/2" className="underline text-blue-400">
            blog2
          </Link>
        </nav>
        <main>
          <h2 className="text-2xl">{new Date().toLocaleTimeString()}</h2>
          <pre>{JSON.stringify(posts, null, 2)}</pre>
          {children}
        </main>
      </body>
    </html>
  );
}
